### ISSUE TITLE
Hey thanks for a free API key

### ISSUE THREAD

**Issue by copperstick6** [glooga/speakchat#1]
You should really consider using a .gitignore

**Comment by jaflo** [comment]
Thank you for sharing your concern copperstick6! The IBM API tokens in `routes/index.js` (which I assume you are referring to) are invalid and cannot be used to make requests. There is a `.gitignore` present in the root directory (you might need to change your file manager settings to show hidden files) and the entire file would need to be ignored, which isn't feasible. A possible change would be to put the tokens into a different file that is ignored or environment variables, which are then referred to in `index.js`. Might make that change sometime in the future.
